# Generated by Django 2.0.7 on 2018-07-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location_hours',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='location_logo',
            field=models.ImageField(null=True, upload_to='device/images'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location_photo',
            field=models.ImageField(null=True, upload_to='device/images'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ssid_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
