# Generated by Django 2.0.7 on 2018-08-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.AlterField(
            model_name='billing',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='billing',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
    ]
