# Generated by Django 2.0.7 on 2018-07-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingInfo',
            new_name='Billing',
        ),
        migrations.RenameModel(
            old_name='BusinessInfo',
            new_name='Business',
        ),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
