# Generated by Django 2.0.7 on 2018-07-30 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wirfi_app.DateTimeModel')),
                ('stripe_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=128)),
                ('interval', models.CharField(default='month', max_length=128)),
                ('currency', models.CharField(default='usd', max_length=128)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            bases=('wirfi_app.datetimemodel',),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wirfi_app.DateTimeModel')),
                ('customer_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wirfi_app.ServicePlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('wirfi_app.datetimemodel',),
        ),
    ]
