# Generated by Django 2.0.7 on 2018-07-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0002_auto_20180720_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='card_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='billing',
            name='security_code',
            field=models.BigIntegerField(),
        ),
    ]
