# Generated by Django 2.0.7 on 2018-07-31 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0002_serviceplan_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationInfo',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wirfi_app.DateTimeModel')),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('auth_key', models.CharField(max_length=128)),
                ('refresh_token', models.CharField(max_length=128)),
                ('push_notification_token', models.CharField(blank=True, max_length=128)),
                ('device_type', models.IntegerField(blank=True, null=True)),
            ],
            bases=('wirfi_app.datetimemodel',),
        ),
    ]
