# Generated by Django 2.0.7 on 2018-08-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0003_auto_20180814_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
