# Generated by Django 2.0.7 on 2018-08-07 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0004_auto_20180807_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLocationHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('is_on', models.BooleanField(default=True)),
                ('whole_day', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ssid_name',
        ),
        migrations.AddField(
            model_name='devicenetwork',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_network', to='wirfi_app.Device'),
        ),
        migrations.AddField(
            model_name='devicelocationhours',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_hours', to='wirfi_app.Device'),
        ),
    ]
