# Generated by Django 2.0.7 on 2018-08-16 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0005_devicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
