# Generated by Django 2.0.7 on 2018-08-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0004_remove_billing_stripe_token'),
        ('wirfi_app', '0005_devicestatus'),
    ]

    operations = [
    ]
