# Generated by Django 2.0.7 on 2018-08-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0006_auto_20180807_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocationhours',
            name='day',
            field=models.CharField(max_length=9),
        ),
    ]
