# Generated by Django 2.0.7 on 2018-08-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0006_auto_20180816_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicestatus',
            old_name='_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='devicestatus',
            old_name='_time',
            new_name='time',
        ),
    ]
