# Generated by Django 2.0.7 on 2018-08-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0006_merge_20180816_0357'),
        ('wirfi_app', '0007_auto_20180816_1042'),
    ]

    operations = [
    ]
