# Generated by Django 2.0.7 on 2018-08-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0007_auto_20180807_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='name',
        ),
    ]
