# Generated by Django 2.0.7 on 2018-08-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0007_auto_20180807_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='location_logo',
            field=models.ImageField(null=True, upload_to='device/images'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location_photo',
            field=models.ImageField(null=True, upload_to='device/images'),
        ),
        migrations.AlterField(
            model_name='device',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=15),
        ),
    ]
