# Generated by Django 2.0.7 on 2018-08-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0008_merge_20180817_0418'),
        ('wirfi_app', '0008_merge_20180816_1054'),
    ]

    operations = [
    ]
