# Generated by Django 2.0.7 on 2018-08-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0008_auto_20180808_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationtoken',
            name='device_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authorizationtoken',
            name='push_notification_token',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
