# Generated by Django 2.0.7 on 2018-08-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0009_auto_20180808_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='strip_token',
            new_name='stripe_token',
        ),
    ]
