# Generated by Django 2.0.7 on 2018-08-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0010_auto_20180821_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
