# Generated by Django 2.0.7 on 2018-08-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0010_auto_20180808_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='customer_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
