# Generated by Django 2.0.7 on 2018-08-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0011_billing_customer_id'),
        ('wirfi_app', '0010_auto_20180809_0518'),
    ]

    operations = [
    ]
