# Generated by Django 2.0.7 on 2018-08-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0012_auto_20180822_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='devices',
        ),
        migrations.AddField(
            model_name='device',
            name='industry_type',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='industry_type', to='wirfi_app.Industry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='status',
            field=models.IntegerField(choices=[(1, 'ONLINE'), (2, 'CELL'), (3, 'AUTO RECOVER'), (4, 'WEAK SIGNAL'), (5, 'OFFLINE'), (6, 'ASLEEP')], default=6),
        ),
    ]
