# Generated by Django 2.0.7 on 2018-08-09 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0012_merge_20180809_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
