# Generated by Django 2.0.7 on 2018-08-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0011_device_priority'),
        ('wirfi_app', '0013_auto_20180822_1126'),
    ]

    operations = [
    ]
