# Generated by Django 2.0.7 on 2018-08-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0013_device_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelocationhours',
            name='whole_day',
        ),
    ]
