# Generated by Django 2.0.7 on 2018-08-24 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0014_merge_20180823_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wirfi_app.Device'),
        ),
    ]
