# Generated by Django 2.0.7 on 2018-08-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0014_remove_devicelocationhours_whole_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelocationhours',
            name='day',
        ),
        migrations.AddField(
            model_name='devicelocationhours',
            name='day_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
