# Generated by Django 2.0.7 on 2018-08-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0015_auto_20180809_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
