# Generated by Django 2.0.7 on 2018-08-29 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0015_auto_20180824_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_muted', models.BooleanField(default=False)),
                ('mute_start', models.DateTimeField(auto_now=True)),
                ('mute_duration', models.IntegerField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_settings', to='wirfi_app.Device')),
            ],
        ),
    ]
