# Generated by Django 2.0.7 on 2018-08-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0017_auto_20180831_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicenotification',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
