# Generated by Django 2.0.7 on 2018-09-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0018_devicenotification_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicenotification',
            name='priority',
        ),
        migrations.AddField(
            model_name='devicesetting',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
