# Generated by Django 2.0.7 on 2018-09-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0019_auto_20180903_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='longitude',
        ),
    ]
