# Generated by Django 2.0.7 on 2018-09-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0020_auto_20180905_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='priority',
        ),
    ]
