# Generated by Django 2.0.7 on 2018-09-07 08:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0021_remove_device_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filter_type', models.PositiveIntegerField()),
                ('filter_keys', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('sort_type', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
