# Generated by Django 2.0.7 on 2018-09-10 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0023_useractivationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivationcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='useractivationcode',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useractivationcode',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useractivationcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
