# Generated by Django 2.0.7 on 2018-09-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0026_auto_20180910_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicenotification',
            name='type',
            field=models.IntegerField(choices=[(1, 'Urgent Unread'), (2, 'Unread'), (3, 'Read')], default=2),
        ),
    ]
