# Generated by Django 2.0.7 on 2018-09-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0027_auto_20180911_0651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presetfilter',
            unique_together={('user', 'name')},
        ),
    ]
