# Generated by Django 2.0.7 on 2018-09-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0027_auto_20180911_0450'),
        ('wirfi_app', '0028_auto_20180911_0737'),
    ]

    operations = [
    ]
