# Generated by Django 2.0.7 on 2018-09-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0028_auto_20180911_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivationcode',
            name='code',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
