# Generated by Django 2.0.7 on 2018-09-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0029_merge_20180911_0828'),
        ('wirfi_app', '0029_auto_20180911_0933'),
    ]

    operations = [
    ]
