# Generated by Django 2.0.7 on 2018-09-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0031_auto_20180913_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecameraservices',
            name='serial_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
