# Generated by Django 2.0.7 on 2018-09-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0032_devicecameraservices_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecameraservices',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_service', to='wirfi_app.Device'),
        ),
    ]
