# Generated by Django 2.0.7 on 2018-09-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0033_auto_20180913_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
