# Generated by Django 2.0.7 on 2018-09-14 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0033_auto_20180913_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestatus',
            name='date',
        ),
        migrations.RemoveField(
            model_name='devicestatus',
            name='time',
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='wirfi_app.Device'),
        ),
    ]
