# Generated by Django 2.0.7 on 2018-09-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0034_device_created_at'),
        ('wirfi_app', '0034_auto_20180914_1148'),
    ]

    operations = [
    ]
