# Generated by Django 2.0.7 on 2018-09-17 12:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0035_merge_20180917_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetfilter',
            name='filter_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None),
        ),
    ]
