# Generated by Django 2.0.7 on 2018-10-14 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0039_auto_20181010_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicenetwork',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_network', to='wirfi_app.Device'),
        ),
    ]
