# Generated by Django 2.0.7 on 2018-10-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0040_auto_20181014_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicenetwork',
            name='primary_network',
            field=models.BooleanField(default=False),
        ),
    ]
