# Generated by Django 2.0.7 on 2018-10-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0041_devicenetwork_primary_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicenetwork',
            name='primary_network',
            field=models.BooleanField(),
        ),
    ]
