# Generated by Django 2.0.7 on 2018-10-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0042_auto_20181023_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesetting',
            name='is_asleep',
            field=models.BooleanField(default=False),
        ),
    ]
