# Generated by Django 2.0.7 on 2018-11-12 08:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0044_auto_20181030_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTaskForWiRFiDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('queued_status', models.BooleanField(default=False)),
            ],
        ),
    ]
