# Generated by Django 2.0.7 on 2018-11-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0047_queuetaskforwirfidevice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location_of_device',
            field=models.CharField(default='Civil Mall', max_length=128, verbose_name='location_of_device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.CharField(max_length=100, verbose_name='device_address'),
        ),
    ]
