# Generated by Django 2.0.7 on 2018-11-26 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0048_auto_20181121_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queuetaskforwirfidevice',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='queuetaskforwirfidevice',
            name='action',
            field=models.CharField(choices=[('primary_network_changed', 'primary_network_changed'), ('secondary_network_changed', 'secondary_network_changed'), ('device_created', 'device_created'), ('no task', 'no task')], default='no task', max_length=64),
        ),
        migrations.AddField(
            model_name='queuetaskforwirfidevice',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='queue_tasks', to='wirfi_app.Device'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='queuetaskforwirfidevice',
            unique_together={('action', 'device')},
        ),
    ]
