# Generated by Django 2.0.7 on 2018-12-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0051_auto_20181214_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.TextField(verbose_name='device_address'),
        ),
    ]
