# Generated by Django 2.0.7 on 2018-12-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0052_auto_20181217_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicenotification',
            name='device_status',
            field=models.CharField(default='6', max_length=2),
            preserve_default=False,
        ),
    ]
