# Generated by Django 2.0.7 on 2019-01-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0057_devicepingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesetting',
            name='has_sleep_feature',
            field=models.BooleanField(default=True),
        ),
    ]
