# Generated by Django 2.0.7 on 2019-01-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0058_auto_20190123_1148'),
        ('wirfi_app', '0058_auto_20190125_0604'),
    ]

    operations = [
    ]
