# Generated by Django 2.0.7 on 2019-01-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirfi_app', '0059_merge_20190125_0606'),
        ('wirfi_app', '0059_profile_push_notifications'),
    ]

    operations = [
    ]
